image: gitpod/workspace-full
tasks:
    - init: mvn compile
      command: mvn exec:java -Dexec.mainClass=Main
      name: Setup script

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview


